# Specify Hosts and Connection Type to use
- hosts: all
  vars:
    ansible_network_os: cisco.ios.ios  # set for a play
  tasks:
    - ios_command:
        command: "{{ cmd }}"
      vars:
        ansible_network_os: cisco.ios.ios  # set for individual task

  tasks:
    - name: Get IOS Facts
      cisco.ios.ios_facts:
        gather_subset: min
        gather_network_resources: interfaces

    - name: Display Device Info
      debug:
        msg:
          - "Hostname: {{ ansible_net_hostname }}"
          - "Serial Number: {{ ansible_net_serialnum }}"
          - "IOS-XE Version: {{ ansible_net_version }}"
          - "Model: {{ ansible_net_model }}"
          - "Interfaces {{ ansible_network_resources['interfaces'] }}"
